# Generated by Django 3.1.7 on 2021-12-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0003_remove_service_invoice_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
