# Generated by Django 3.1.7 on 2021-12-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktury', '0004_invoice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='streetname',
            field=models.CharField(default='ulica', max_length=200),
            preserve_default=False,
        ),
    ]
